workspace:
  base: /go
  path: src/github.com/udistrital/${DRONE_REPO##udistrital/}
  when:
      branch: [master, test]
      event: [push, pull_request]

pipeline:
  grunt-sonar-runner:
    image: timbru31/java-node
    commands:
     - npm install -g grunt-cli bower
     - npm install grunt --save-dev
     - npm install grunt-sonar-runner --save-dev
     - grunt sonarRunner:analysis
    when:
      branch: [test]
      event: push

  # build and test the go program
  nodejs:
    image: node:10.7.0
    commands:
     - npm install -g grunt-cli bower
     - npm install natives
     - npm install
     - bower install --allow-root
     - grunt build
    when:
      branch: [master, test]
      event: [push, pull_request]

  # upload files to bucket s3 cliente-test
  publish_s3_test:
    image: plugins/s3
    secrets: [ aws_access_key_id, aws_secret_access_key ]
    region: "us-east-1"
    bucket: "cliente-pruebas"
    source: dist/**/*
    target: /pruebas${DRONE_REPO_NAME%%_cliente}.portaloas.udistrital.edu.co
    strip_prefix: dist/
    when:
      branch: test
      event: [push, pull_request]

  # upload files to bucket s3 cliente-prod
  publish_s3_prod:
    image: plugins/s3
    secrets: [ aws_access_key_id, aws_secret_access_key ]
    region: "us-east-1"
    bucket: "cliente-prod"
    source: dist/**/*
    target: /${DRONE_REPO_NAME%%_cliente}.portaloas.udistrital.edu.co
    strip_prefix: dist/
    when:
      branch: master
      event: [push, pull_request]

  #Notify results to telegram
  notify_telegram:
    image: appleboy/drone-telegram
    secrets: [ telegram_token, telegram_to ]
    format: html
    message: >
      {{#success build.status}}
        <code>{{repo.owner}}/{{repo.name}}</code> <a href="{{build.link}}">SUCCESS</a>
        <code>{{commit.branch}}</code>@<a href="{{commit.link}}">{{truncate commit.sha 7}}</a>
      {{else}}
        <code>{{repo.owner}}/{{repo.name}}</code> <a href="{{build.link}}">FAILURE</a>
        <code>{{commit.branch}}</code>@<a href="{{commit.link}}">{{truncate commit.sha 7}}</a>
      {{/success}}
    when:
      status: [success, failure]
      branch: [master, test]
      event: [push, pull_request]
